export const defaultEventDisclaimer = `Terrier Pursuit — Participation Acknowledgment and Media Consent

Terrier Pursuit is a voluntary team activity that may involve walking, using public transportation, crossing streets, and visiting public locations throughout Boston. Participation involves ordinary risks associated with travel in an urban environment, including traffic, weather, uneven surfaces, crowds, and physical exertion.

Participants are responsible for making safe decisions, remaining with their team, following all applicable laws and Boston University policies, respecting people and property, and avoiding restricted, private, unsafe, or hazardous areas. Clues never require trespassing, unsafe conduct, or entering a location where photography is prohibited. The game does not provide turn-by-turn directions or continuously monitor participants. If a situation feels unsafe, participants should stop, move to a safe place, and contact the organizer. For an emergency, call 911 or the appropriate BU emergency service.

Team members will take and upload photographs as proof of completing clues. Participants must obtain permission from identifiable teammates before uploading a photograph and should avoid photographing bystanders without permission. Uploaded photographs, participant details, team information, and consent records may be stored and reviewed to administer the event, confirm results, select winners, and support event follow-up.

By accepting the media consent below, I authorize Trustees of Boston University and its representatives to use submitted photographs that include my likeness or name for Terrier Pursuit and related Boston University educational, informational, or promotional communications, including websites, social media, print, and presentations, without compensation. I understand that submitted photographs may be downloaded by the event organizer for these purposes.

Participation is voluntary. This acknowledgment is a prototype event notice and does not replace any waiver or release that Boston University Risk Management, the sponsoring school or department, or another authorized University office may require. The sponsoring office should review and approve the final wording before publishing the event.`;
